@baseUrl = http://localhost:3000

### Get configs
POST {{baseUrl}}/api/get-configs

### send email
POST {{baseUrl}}/api/demo/send-email
Content-Type: application/json

{
  "emails": ["support@thinkany.ai"],
  "subject": "Test Send Email",
  "content": "This is a test email from ShipAny"
}

### generate music
POST {{baseUrl}}/api/ai/generate
Content-Type: application/json

{
  "type": "music",
  "provider": "kie",
  "model": "V5",
  "prompt": "a simple song about happy birthday."
}

### generate image
POST {{baseUrl}}/api/ai/generate
Content-Type: application/json

{
  "type": "image",
  "provider": "fal",
  "model": "google/nano-banana",
  "prompt": "two cats are running.",
  "num": 1,
  "options": {
    "image_input": ["https://replicate.delivery/pbxt/NbYIclp4A5HWLsJ8lF5KgiYSNaLBBT1jUcYcHYQmN1uy5OnN/tmpcqc07f_q.png","https://replicate.delivery/pbxt/NbYId45yH8s04sptdtPcGqFIhV7zS5GTcdS3TtNliyTAoYPO/Screenshot%202025-08-26%20at%205.30.12%E2%80%AFPM.png"]
  }
}

### ai query 
POST {{baseUrl}}/api/ai/query
Content-Type: application/json 

{
  "taskId": "a936e86e21c504a773bd0932a6885bdb"
}

### generate text
POST {{baseUrl}}/api/demo/gen-text
Content-Type: application/json

{
  "model": "openai/gpt-5",
  "prompt": "What is the capital of France?"
}

### create payment
POST {{baseUrl}}/api/demo/payment
Content-Type: application/json

{
  "amount": 122,
  "currency": "hkd",
  "provider": "paypal",
  "product_id": "prod_7ehwYVBKhykl9mAFBcPibQ",
  "email": "me@idoubi.cc"
}